import { useState, useRef } from 'react';
import { createWorker } from 'tesseract.js';
import Card from '../components/Card/Card.jsx';
import Button from '../components/Button/Button.jsx';
import './RegistrationPage.css';

const FORM_STEPS = [
  { id: 'personal', title: 'Personal Details', icon: '👤' },
  { id: 'address', title: 'Address & Residence', icon: '🏠' },
  { id: 'documents', title: 'Documentation', icon: '📄' },
  { id: 'review', title: 'AI Review', icon: '🤖' }
];

// Real ECI voter registration tutorial videos
const TUTORIAL_VIDEOS = [
  {
    id: 1,
    title: 'How to Apply for Voter ID Card Online',
    videoId: 'OJtmNBgpvCI',
    duration: '4:32'
  },
  {
    id: 2,
    title: 'How to Fill Form 6 — Step by Step',
    videoId: 'pCVZnMFMbNk',
    duration: '6:15'
  },
  {
    id: 3,
    title: 'Documents Required for Voter Registration',
    videoId: '1pXp3JJfSSE',
    duration: '3:48'
  }
];

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
const GENDERS = ['Male', 'Female', 'Transgender'];
const RELATION_TYPES = ['Father', 'Mother', 'Husband', 'Guardian'];

function calculateAge(dob) {
  if (!dob) return '';
  const today = new Date();
  const birthDate = new Date(dob);
  let age = today.getFullYear() - birthDate.getFullYear();
  const m = today.getMonth() - birthDate.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) age--;
  return age;
}

// Document Verification Report Component
function ReviewReport({ data }) {
  if (!data) return null;

  const scoreColor = data.overallScore >= 8 ? '#22c55e' : data.overallScore >= 5 ? '#f59e0b' : '#ef4444';

  return (
    <div className="report-card animate-fade-in">

      {/* Header */}
      <div className="report-header">
        <div>
          <h3>📋 Application Verification Report</h3>
          <p className="report-meta">Generated by CivicQ AI — Form 6 Review</p>
        </div>
        <div className="report-score" style={{ '--score-color': scoreColor }}>
          <span className="score-num">{data.overallScore}</span>
          <span className="score-denom">/10</span>
        </div>
      </div>

      {/* Eligibility Banner */}
      {data.eligibility && (
        <div className={`eligibility-banner ${data.eligibility.ageEligible ? 'eligible' : 'not-eligible'}`}>
          <span className="elig-icon">{data.eligibility.ageEligible ? '✅' : '❌'}</span>
          <div>
            <strong>Age Eligibility</strong>
            <span>{data.eligibility.note}</span>
          </div>
        </div>
      )}

      {/* Document Detection */}
      {data.documentSummary && (
        <div className="doc-detection">
          <div className="doc-detection-header">
            <span>📄</span>
            <strong>Document Analysis</strong>
          </div>
          <p>{data.documentSummary}</p>
        </div>
      )}

      {/* Verification Table */}
      {data.verificationChecks && data.verificationChecks.length > 0 && (
        <div className="verification-section">
          <h4>🔍 Document vs. Form Verification</h4>
          <div className="verification-table">
            <div className="vt-header">
              <span>Field</span>
              <span>You Entered</span>
              <span>Found in Document</span>
              <span>Status</span>
            </div>
            {data.verificationChecks.map((check, i) => (
              <div key={i} className={`vt-row ${check.match ? 'match' : 'mismatch'}`}>
                <span className="vt-field">{check.field}</span>
                <span className="vt-value">{check.formValue || '—'}</span>
                <span className="vt-value">{check.docValue || 'Not found'}</span>
                <span className="vt-status">{check.match ? '✅' : '❌'}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Issues */}
      {data.issues && data.issues.length > 0 && (
        <div className="report-issues">
          <h4>⚠️ Issues Found</h4>
          <ul>
            {data.issues.map((issue, i) => <li key={i}>{issue}</li>)}
          </ul>
        </div>
      )}

      {/* Recommendations */}
      {data.recommendations && data.recommendations.length > 0 && (
        <div className="report-recs">
          <h4>💡 Recommendations</h4>
          <ul>
            {data.recommendations.map((rec, i) => <li key={i}>{rec}</li>)}
          </ul>
        </div>
      )}

      {/* Summary narrative */}
      <div className="report-narrative">
        <h4>📝 Summary</h4>
        <p>{data.summary}</p>
      </div>

      {/* Verdict */}
      <div className="report-verdict">
        <span className={`verdict-badge verdict-${data.verdict}`}>
          {data.verdict === 'ready' ? '✅ Ready to Submit'
            : data.verdict === 'review' ? '⚠️ Needs Review'
            : '❌ Incomplete — Please fix issues'}
        </span>
      </div>
    </div>
  );
}

export default function RegistrationPage() {
  const [step, setStep] = useState(0);
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    dob: '',
    gender: '',
    bloodGroup: '',
    mobile: '',
    email: '',
    relationType: 'Father',
    relationName: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    docType: 'Aadhar Card',
  });

  const [file, setFile] = useState(null);
  const [ocrText, setOcrText] = useState('');
  const [ocrLoading, setOcrLoading] = useState(false);
  const [ocrProgress, setOcrProgress] = useState(0);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState(null);
  const [reviewResult, setReviewResult] = useState(null);
  const [activeVideo, setActiveVideo] = useState(null);
  const fileRef = useRef(null);

  const age = calculateAge(formData.dob);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleFileChange = async (e) => {
    const selected = e.target.files[0];
    if (!selected) return;
    setFile(selected);
    setOcrText('');
    setOcrProgress(0);

    // Only run OCR on image files
    if (!selected.type.startsWith('image/')) {
      setOcrText('[PDF uploaded — AI will review form fields only]');
      return;
    }

    setOcrLoading(true);
    try {
      const worker = await createWorker('eng', 1, {
        logger: (m) => {
          if (m.status === 'recognizing text') {
            setOcrProgress(Math.round(m.progress * 100));
          }
        }
      });
      const { data: { text, confidence } } = await worker.recognize(selected);
      await worker.terminate();
      
      // Debug: print OCR result to browser console
      console.group('🔍 Tesseract OCR Result');
      console.log(`📊 Confidence: ${confidence.toFixed(1)}%`);
      console.log('📝 Extracted Text:\n', text || '(empty)');
      console.groupEnd();
      
      setOcrText(text);
    } catch (err) {
      console.error('OCR error:', err);
      setOcrText('[OCR failed — AI will review form fields only]');
    } finally {
      setOcrLoading(false);
    }
  };

  const getAiInfo = async (field) => {
    setAiLoading(true);
    setAiResponse(null);
    try {
      const res = await fetch('http://127.0.0.1:3001/api/chat/message', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `Explain in 2-3 short bullet points exactly what the '${field}' field requires in India's Voter Registration Form 6. Include what documents are valid. Be concise.`,
          mode: 'normal'
        }),
      });
      if (!res.ok) throw new Error(`Server error ${res.status}`);
      const data = await res.json();
      setAiResponse({ field, text: data.response });
    } catch (err) {
      setAiResponse({ field, text: `Could not reach AI assistant (${err.message}).` });
    } finally {
      setAiLoading(false);
    }
  };

  const runAiReview = async () => {
    setAiLoading(true);
    try {
      const reviewPayload = {
        ...formData,
        age,
        documentScanned: file ? file.name : 'None',
        ocrExtractedText: ocrText || 'No document scanned',
      };

      const hasDoc = file !== null;
      const hasOcr = ocrText && !ocrText.startsWith('[');

      const prompt = `You are an Indian Election Commission verification officer reviewing a Form 6 voter registration application.

FORM DATA SUBMITTED:
${JSON.stringify({ ...formData, age }, null, 2)}

DOCUMENT UPLOADED: ${hasDoc ? file.name : 'No document uploaded'}
OCR EXTRACTED TEXT FROM DOCUMENT:
${hasOcr ? ocrText : 'No readable text could be extracted'}

YOUR TASK:
1. Analyze the form data for completeness and correctness per ECI Form 6 requirements.
2. If OCR text is available, extract the applicant's name, date of birth, and address from it and compare against what was submitted in the form. Flag any mismatches.
3. Check age eligibility (must be 18+).
4. Return ONLY a valid JSON object — no markdown, no backticks, no extra text.

REQUIRED JSON STRUCTURE:
{
  "overallScore": <integer 1-10>,
  "verdict": <"ready" | "review" | "incomplete">,
  "eligibility": {
    "ageEligible": <true|false>,
    "note": "<e.g. Applicant is 22 years old, eligible to vote>"
  },
  "documentSummary": "<What document was detected and what key fields were extracted from OCR. If no doc, state that.>",
  "verificationChecks": [
    {
      "field": "<e.g. Full Name>",
      "formValue": "<what user typed>",
      "docValue": "<what was found in OCR text, or 'Not found in document'>",
      "match": <true|false>,
      "note": "<brief explanation of match or mismatch>"
    }
  ],
  "issues": ["<specific issue 1>", "<specific issue 2>"],
  "recommendations": ["<actionable fix 1>", "<actionable fix 2>"],
  "summary": "<2-3 sentence narrative assessment of the overall application quality and next steps>"
}`;

      const res = await fetch('http://127.0.0.1:3001/api/chat/message', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: prompt, mode: 'normal' }),
      });

      if (!res.ok) throw new Error(`Server error ${res.status}`);

      const data = await res.json();

      // Safely parse JSON — handle AI wrapping in backticks or prose
      let parsed;
      try {
        const match = data.response.match(/\{[\s\S]*\}/);
        parsed = match ? JSON.parse(match[0]) : null;
      } catch {
        parsed = null;
      }

      if (!parsed) {
        // Fallback: show raw response if JSON parse fails
        parsed = {
          overallScore: 5,
          verdict: 'review',
          summary: data.response,
          documentSummary: null,
          verificationChecks: [],
          issues: ['AI could not generate a structured report. Raw response shown in summary.'],
          recommendations: ['Try again or check your internet connection.'],
          eligibility: { ageEligible: age >= 18, note: `Age is ${age}` }
        };
      }

      setReviewResult(parsed);
      setStep(3);
    } catch (err) {
      alert(`AI Review failed: ${err.message}. Please ensure the backend server is running.`);
    } finally {
      setAiLoading(false);
    }
  };

  const renderStep = () => {
    switch (step) {
      case 0:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-grid-2">
              <div className="form-group">
                <label>First Name <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('First Name')}>💡</button></label>
                <input name="firstName" value={formData.firstName} onChange={handleInputChange} placeholder="As per ID document" />
              </div>
              <div className="form-group">
                <label>Last Name <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Last Name')}>💡</button></label>
                <input name="lastName" value={formData.lastName} onChange={handleInputChange} placeholder="Surname" />
              </div>
            </div>

            <div className="form-grid-3">
              <div className="form-group">
                <label>Date of Birth <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Date of Birth')}>💡</button></label>
                <input type="date" name="dob" value={formData.dob} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>Age</label>
                <input value={age ? `${age} years` : '—'} readOnly className="readonly-input" />
              </div>
              <div className="form-group">
                <label>Gender <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Gender')}>💡</button></label>
                <select name="gender" value={formData.gender} onChange={handleInputChange}>
                  <option value="">Select</option>
                  {GENDERS.map(g => <option key={g}>{g}</option>)}
                </select>
              </div>
            </div>

            <div className="form-grid-2">
              <div className="form-group">
                <label>Blood Group <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Blood Group')}>💡</button></label>
                <select name="bloodGroup" value={formData.bloodGroup} onChange={handleInputChange}>
                  <option value="">Select</option>
                  {BLOOD_GROUPS.map(b => <option key={b}>{b}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label>Mobile Number <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Mobile Number')}>💡</button></label>
                <input name="mobile" value={formData.mobile} onChange={handleInputChange} placeholder="+91 XXXXX XXXXX" maxLength={13} />
              </div>
            </div>

            <div className="form-grid-2">
              <div className="form-group">
                <label>Relation Type <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Relation Type (Father/Husband name)')}>💡</button></label>
                <select name="relationType" value={formData.relationType} onChange={handleInputChange}>
                  {RELATION_TYPES.map(r => <option key={r}>{r}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label>Relation's Name</label>
                <input name="relationName" value={formData.relationName} onChange={handleInputChange} placeholder="Name as per ID" />
              </div>
            </div>
          </div>
        );

      case 1:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-group">
              <label>Full Address <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Residential Address')}>💡</button></label>
              <textarea name="address" value={formData.address} onChange={handleInputChange} placeholder="House/Flat No, Street Name, Landmark..." rows="3" />
            </div>
            <div className="form-grid-3">
              <div className="form-group">
                <label>City / Town</label>
                <input name="city" value={formData.city} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>State</label>
                <input name="state" value={formData.state} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>PIN Code <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('PIN Code')}>💡</button></label>
                <input name="pincode" value={formData.pincode} onChange={handleInputChange} maxLength={6} placeholder="6-digit" />
              </div>
            </div>
            <div className="form-group">
              <label>Email Address (Optional)</label>
              <input type="email" name="email" value={formData.email} onChange={handleInputChange} placeholder="For ECI notifications" />
            </div>
          </div>
        );

      case 2:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-group">
              <label>Primary ID Proof Type <button className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Identity and Age Proof document')}>💡</button></label>
              <select name="docType" value={formData.docType} onChange={handleInputChange}>
                <option>Aadhar Card</option>
                <option>PAN Card</option>
                <option>Driving License</option>
                <option>Passport</option>
                <option>Birth Certificate</option>
                <option>Bank Passbook</option>
              </select>
            </div>

            <div className="upload-container">
              <input
                type="file"
                id="file-upload"
                ref={fileRef}
                className="hidden-input"
                onChange={handleFileChange}
                accept="image/*,.pdf"
              />
              <label htmlFor="file-upload" className={`upload-placeholder glass ${ocrLoading ? 'scanning' : ''}`}>
                {ocrLoading ? (
                  <div className="ocr-progress">
                    <div className="ocr-spinner" />
                    <span>Scanning document... {ocrProgress}%</span>
                    <div className="ocr-bar"><div style={{ width: `${ocrProgress}%` }} /></div>
                  </div>
                ) : file ? (
                  <div className="file-success">
                    <span className="file-icon">📄</span>
                    <span className="file-name">✅ {file.name}</span>
                    {ocrText && !ocrText.startsWith('[') && (
                      <span className="ocr-badge">🔍 Text extracted</span>
                    )}
                  </div>
                ) : (
                  <div className="upload-prompt">
                    <span className="upload-icon">📁</span>
                    <span>Click to Upload ID Document</span>
                    <span className="upload-hint">JPG, PNG, or PDF • Max 10MB • AI will scan for verification</span>
                  </div>
                )}
              </label>
            </div>

            {ocrText && (
              <details className="ocr-preview">
                <summary>🔍 View extracted text from document</summary>
                <pre>{ocrText}</pre>
              </details>
            )}
          </div>
        );

      case 3:
        return (
          <div className="form-section animate-slide-up">
            {reviewResult ? (
              <ReviewReport data={reviewResult} />
            ) : (
              <div className="review-placeholder">
                <span>No review generated yet.</span>
              </div>
            )}
          </div>
        );

      default: return null;
    }
  };

  return (
    <main className="registration-page">
      <div className="registration-layout">
        {/* ---- Main Form ---- */}
        <div className="registration-main">
          <header className="registration-header">
            <h1>
              <span className="heading-neuro">Registration</span>{' '}
              <span className="text-gradient">Hub</span>
            </h1>
            <p>Practice filling Form 6 — AI scans your documents & reviews your application</p>
          </header>

          <div className="step-indicator">
            {FORM_STEPS.map((s, i) => (
              <div key={s.id} className={`step-item ${i === step ? 'active' : ''} ${i < step ? 'completed' : ''}`}>
                <span className="step-icon">{s.icon}</span>
                <span className="step-label">{s.title}</span>
              </div>
            ))}
          </div>

          <Card variant="glass" className="form-card">
            {renderStep()}

            {/* AI Info Bubble */}
            {aiResponse && (
              <div className="ai-bubble animate-fade-in">
                <div className="ai-bubble-header">
                  <span>🤖 About: <strong>{aiResponse.field}</strong></span>
                  <button onClick={() => setAiResponse(null)}>✕</button>
                </div>
                <p>{aiResponse.text}</p>
              </div>
            )}

            <div className="form-footer">
              {step > 0 && step < 3 && (
                <Button variant="secondary" onClick={() => { setStep(step - 1); setAiResponse(null); }}>← Back</Button>
              )}
              {step < 2 && (
                <Button variant="primary" onClick={() => { setStep(step + 1); setAiResponse(null); }}>Next Step →</Button>
              )}
              {step === 2 && (
                <Button variant="primary" onClick={runAiReview} disabled={aiLoading || ocrLoading}>
                  {aiLoading ? '🤖 Analyzing...' : '🚀 Generate AI Review'}
                </Button>
              )}
              {step === 3 && (
                <Button variant="secondary" onClick={() => { setStep(0); setReviewResult(null); setFile(null); setOcrText(''); }}>
                  🔄 Start Fresh
                </Button>
              )}
            </div>
          </Card>
        </div>

        {/* ---- Sidebar ---- */}
        <aside className="registration-sidebar">
          <Card variant="bento" className="video-panel">
            <h3>📖 Tutorial Hub</h3>
            <p className="panel-subtitle">Official guides for voter registration in India.</p>

            <div className="video-list">
              {TUTORIAL_VIDEOS.map(video => (
                <div key={video.id} className={`video-item glass ${activeVideo === video.id ? 'active' : ''}`}>
                  {activeVideo === video.id ? (
                    <div className="video-thumb">
                      <iframe
                        src={`https://www.youtube.com/embed/${video.videoId}?autoplay=1`}
                        title={video.title}
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                      />
                    </div>
                  ) : (
                    <button className="video-preview-btn" onClick={() => setActiveVideo(video.id)}>
                      <div className="yt-thumbnail">
                        <img
                          src={`https://img.youtube.com/vi/${video.videoId}/mqdefault.jpg`}
                          alt={video.title}
                        />
                        <div className="yt-play-overlay">▶</div>
                      </div>
                    </button>
                  )}
                  <div className="video-info">
                    <h4>{video.title}</h4>
                    <span>⏱️ {video.duration}</span>
                    {activeVideo === video.id && (
                      <button className="close-video" onClick={() => setActiveVideo(null)}>✕ Close</button>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className="official-link">
              <a href="https://voters.eci.gov.in/" target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm w-full">
                🏛️ Visit Official ECI Portal
              </a>
            </div>
          </Card>
        </aside>
      </div>
    </main>
  );
}
