import { useState, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { createWorker } from 'tesseract.js';
import * as pdfjsLib from 'pdfjs-dist';
import pdfjsWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import Card from '../components/Card/Card.jsx';
import Button from '../components/Button/Button.jsx';
import './RegistrationPage.css';

// Use Vite's ?url import to serve the worker file from the bundle
pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorkerUrl;


const FORM_STEPS = [
  { id: 'personal', title: 'Personal Details', icon: '👤' },
  { id: 'address', title: 'Address & Residence', icon: '🏠' },
  { id: 'documents', title: 'Documentation', icon: '📄' },
  { id: 'review', title: 'AI Review', icon: '🤖' }
];

// Real ECI voter registration tutorial videos
const TUTORIAL_VIDEOS = [
  {
    id: 1,
    title: 'How to Apply for Voter ID Card Online',
    videoId: 'aQ0ZB2-U_-I',
    duration: '18:51'
  },
  {
    id: 2,
    title: 'How to Fill Form 6 — Step by Step',
    videoId: '4IfW6fLDgts',
    duration: '14:49'
  },
  {
    id: 3,
    title: 'Documents Required for Voter Registration',
    videoId: 'j46gEoqzuRY',
    duration: '2:49'
  }
];

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
const GENDERS = ['Male', 'Female', 'Transgender'];
const RELATION_TYPES = ['Father', 'Mother', 'Husband', 'Guardian'];

function calculateAge(dob) {
  if (!dob) return '';
  const today = new Date();
  const birthDate = new Date(dob);
  let age = today.getFullYear() - birthDate.getFullYear();
  const m = today.getMonth() - birthDate.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) age--;
  return age;
}

// Document Verification Report Component
// Handles both structured JSON data AND raw text fallback
function ReviewReport({ data }) {
  if (!data) return null;

  // If we got raw text (JSON parse failed), render it nicely
  if (data._isRawText) {
    return (
      <div className="report-card animate-fade-in">
        <div className="report-header">
          <div>
            <h3>📋 Application Verification Report</h3>
            <p className="report-meta">Generated by CivicQ AI — Form 6 Review</p>
          </div>
        </div>
        <div className="report-narrative raw-report">
          {data.rawText.split('\n').map((line, i) => {
            if (!line.trim()) return <br key={i} />;
            if (line.startsWith('###')) return <h4 key={i}>{line.replace(/^#+\s*/, '')}</h4>;
            if (line.startsWith('##')) return <h3 key={i}>{line.replace(/^#+\s*/, '')}</h3>;
            if (line.startsWith('* **') || line.startsWith('- **')) {
              const match = line.match(/[*-]\s*\*\*(.+?)\*\*:?\s*(.*)/);
              if (match) return <p key={i}><strong>{match[1]}:</strong> {match[2]}</p>;
            }
            if (line.startsWith('* ') || line.startsWith('- ')) {
              return <p key={i} className="report-bullet">• {line.replace(/^[*-]\s*/, '')}</p>;
            }
            if (line.match(/^\d+\.\s/)) {
              return <p key={i} className="report-bullet">{line}</p>;
            }
            return <p key={i}>{line}</p>;
          })}
        </div>
      </div>
    );
  }

  // Structured JSON report
  const scoreColor = data.overallScore >= 8 ? '#22c55e' : data.overallScore >= 5 ? '#f59e0b' : '#ef4444';

  return (
    <div className="report-card animate-fade-in">
      <div className="report-header">
        <div>
          <h3>📋 Application Verification Report</h3>
          <p className="report-meta">Generated by CivicQ AI — Form 6 Review</p>
        </div>
        <div className="report-score" style={{ '--score-color': scoreColor }}>
          <span className="score-num">{data.overallScore}</span>
          <span className="score-denom">/10</span>
        </div>
      </div>

      {data.eligibility && (
        <div className={`eligibility-banner ${data.eligibility.ageEligible ? 'eligible' : 'not-eligible'}`}>
          <span className="elig-icon">{data.eligibility.ageEligible ? '✅' : '❌'}</span>
          <div>
            <strong>Age Eligibility</strong>
            <span>{data.eligibility.note}</span>
          </div>
        </div>
      )}

      {data.documentSummary && (
        <div className="doc-detection">
          <div className="doc-detection-header">
            <span>📄</span>
            <strong>Document Analysis</strong>
          </div>
          <p>{data.documentSummary}</p>
        </div>
      )}

      {data.verificationChecks && data.verificationChecks.length > 0 && (
        <div className="verification-section">
          <h4>🔍 Document vs. Form Verification</h4>
          <div className="verification-table">
            <div className="vt-header">
              <span>Field</span>
              <span>You Entered</span>
              <span>Found in Document</span>
              <span>Status</span>
            </div>
            {data.verificationChecks.map((check, i) => (
              <div key={i} className={`vt-row ${check.match ? 'match' : 'mismatch'}`}>
                <span className="vt-field">{check.field}</span>
                <span className="vt-value">{check.formValue || '—'}</span>
                <span className="vt-value">{check.docValue || 'Not found'}</span>
                <span className="vt-status">{check.match ? '✅' : '❌'}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.issues && data.issues.length > 0 && (
        <div className="report-issues">
          <h4>⚠️ Issues Found</h4>
          <ul>
            {data.issues.map((issue, i) => <li key={i}>{issue}</li>)}
          </ul>
        </div>
      )}

      {data.recommendations && data.recommendations.length > 0 && (
        <div className="report-recs">
          <h4>💡 Recommendations</h4>
          <ul>
            {data.recommendations.map((rec, i) => <li key={i}>{rec}</li>)}
          </ul>
        </div>
      )}

      {data.summary && (
        <div className="report-narrative">
          <h4>📝 Summary</h4>
          <p>{data.summary}</p>
        </div>
      )}

      <div className="report-verdict">
        <span className={`verdict-badge verdict-${data.verdict || 'review'}`}>
          {data.verdict === 'ready' ? '✅ Ready to Submit'
            : data.verdict === 'incomplete' ? '❌ Incomplete — Please fix issues'
            : '⚠️ Needs Review'}
        </span>
      </div>
    </div>
  );
}

export default function RegistrationPage() {
  const { t } = useTranslation();
  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';
  const [step, setStep] = useState(0);

  // We move FORM_STEPS inside the component to use the translation hook
  const FORM_STEPS = [
    { id: 'personal', title: t('registrationPage.formDetails'), icon: '👤' },
    { id: 'address', title: 'Address & Residence', icon: '🏠' },
    { id: 'documents', title: t('registrationPage.docUploadTitle'), icon: '📄' },
    { id: 'review', title: t('registrationPage.aiAnalysis'), icon: '🤖' }
  ];

  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    dob: '',
    gender: '',
    bloodGroup: '',
    mobile: '',
    email: '',
    relationType: 'Father',
    relationName: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    docType: 'Aadhar Card',
  });

  const [file, setFile] = useState(null);
  const [ocrText, setOcrText] = useState('');
  const [ocrLoading, setOcrLoading] = useState(false);
  const [ocrProgress, setOcrProgress] = useState(0);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState(null);
  const [reviewResult, setReviewResult] = useState(null);
  const [activeVideo, setActiveVideo] = useState(null);
  const fileRef = useRef(null);

  const age = calculateAge(formData.dob);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  /**
   * Extract embedded text from a PDF.
   * Supports password-protected PDFs (e.g. Aadhar from UIDAI).
   */
  const extractPdfText = async (file, password = '') => {
    const arrayBuffer = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({
      data: new Uint8Array(arrayBuffer),
      ...(password ? { password } : {})
    });
    const pdf = await loadingTask.promise;
    let fullText = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items.map(item => item.str).join(' ');
      fullText += pageText + '\n';
    }
    return { text: fullText.trim(), pdf };
  };

  /**
   * Render first page of a PDF to a canvas data URL for OCR.
   */
  const renderPdfToImage = async (file, password = '') => {
    const arrayBuffer = await file.arrayBuffer();
    const loadingTask = pdfjsLib.getDocument({
      data: new Uint8Array(arrayBuffer),
      ...(password ? { password } : {})
    });
    const pdf = await loadingTask.promise;
    const page = await pdf.getPage(1);

    // Render at 2x scale for better OCR quality
    const scale = 2.0;
    const viewport = page.getViewport({ scale });
    const canvas = document.createElement('canvas');
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    const ctx = canvas.getContext('2d');

    await page.render({ canvasContext: ctx, viewport }).promise;

    // Convert to greyscale + boost contrast for OCR
    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const data = imageData.data;
    for (let i = 0; i < data.length; i += 4) {
      const grey = 0.299 * data[i] + 0.587 * data[i+1] + 0.114 * data[i+2];
      const boosted = ((grey - 128) * 1.5) + 128;
      const clamped = Math.max(0, Math.min(255, boosted));
      data[i] = data[i+1] = data[i+2] = clamped;
    }
    ctx.putImageData(imageData, 0, 0);

    return canvas.toDataURL('image/png');
  };

  /**
   * Preprocess an image for better OCR (greyscale + contrast boost).
   */
  const preprocessImage = (file) => {
    return new Promise((resolve) => {
      const img = new Image();
      const url = URL.createObjectURL(file);
      img.onload = () => {
        const canvas = document.createElement('canvas');
        const scale = Math.max(1, 1800 / Math.max(img.width, img.height));
        canvas.width = img.width * scale;
        canvas.height = img.height * scale;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imageData.data;
        for (let i = 0; i < data.length; i += 4) {
          const grey = 0.299 * data[i] + 0.587 * data[i+1] + 0.114 * data[i+2];
          const boosted = ((grey - 128) * 1.6) + 128;
          data[i] = data[i+1] = data[i+2] = Math.max(0, Math.min(255, boosted));
        }
        ctx.putImageData(imageData, 0, 0);
        URL.revokeObjectURL(url);
        resolve(canvas.toDataURL('image/png'));
      };
      img.onerror = () => { URL.revokeObjectURL(url); resolve(null); };
      img.src = url;
    });
  };

  const handleFileChange = async (e) => {
    const selected = e.target.files[0];
    if (!selected) return;
    setFile(selected);
    setOcrText('');
    setOcrProgress(0);
    setOcrLoading(true);

    try {
      if (selected.type === 'application/pdf') {
        let text = '';
        
        try {
          const result = await extractPdfText(selected);
          text = result.text;
        } catch (_) {}

        if (text && text.trim().length >= 15) {
          setOcrText(text);
          return;
        }

        let pdfImage = null;
        try {
          pdfImage = await renderPdfToImage(selected);
        } catch (_) {}

        if (!pdfImage) {
          setOcrText('🔒 Could not open PDF. Please ensure it is not password-protected and try again.');
          return;
        }

        const worker = await createWorker('eng', 3, {
          logger: (m) => {
            if (m.status === 'recognizing text') {
              setOcrProgress(Math.round(m.progress * 100));
            }
          }
        });

        const { data: { text: ocrResult } } = await worker.recognize(pdfImage);
        await worker.terminate();

        if (ocrResult && ocrResult.trim().length >= 10) {
          setOcrText(ocrResult);
        } else {
          setOcrText('[PDF scanned but OCR could not extract readable text. Try a clearer document.]');
        }
        return;
      }

      const processedDataUrl = await preprocessImage(selected);

      const worker = await createWorker('eng', 3, {
        logger: (m) => {
          if (m.status === 'recognizing text') {
            setOcrProgress(Math.round(m.progress * 100));
          }
        }
      });

      const { data: { text } } = await worker.recognize(processedDataUrl || selected);
      await worker.terminate();

      setOcrText(!text || text.trim().length < 10
        ? '[Low confidence scan — ensure the document is well-lit and in focus]'
        : text
      );
    } catch (err) {
      setOcrText('[Processing failed — AI will review form fields only]');
    } finally {
      setOcrLoading(false);
    }
  };



  const getAiInfo = async (field) => {
    setAiLoading(true);
    setAiResponse(null);
    try {
      const res = await fetch(`${API_URL}/api/chat/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `Explain in 2-3 short bullet points exactly what the '${field}' field requires in India's Voter Registration Form 6. Include what documents are valid. Be concise.`,
          mode: 'normal'
        }),
      });
      if (!res.ok) throw new Error(`Server error ${res.status}`);
      const data = await res.json();
      setAiResponse({ field, text: data.response });
    } catch (err) {
      setAiResponse({ field, text: `Could not reach AI assistant (${err.message}).` });
    } finally {
      setAiLoading(false);
    }
  };

  const runAiReview = async () => {
    setAiLoading(true);
    try {
      const hasDoc = file !== null;
      // Only consider it valid OCR if it's real text, not one of our error/status messages
      const hasOcr = ocrText
        && ocrText.length > 20
        && !ocrText.startsWith('[')
        && !ocrText.includes('Could not unlock')
        && !ocrText.includes('no extractable text')
        && !ocrText.includes('Low confidence')
        && !ocrText.includes('Processing failed');

      const prompt = `IMPORTANT: You MUST respond with ONLY a raw JSON object. No markdown. No backticks. No explanation. Just the JSON.

You are verifying an Indian voter registration (Form 6).

APPLICANT FORM DATA:
Name: ${formData.firstName} ${formData.lastName}
DOB: ${formData.dob} (Age: ${age})
Gender: ${formData.gender || 'Not provided'}
Blood Group: ${formData.bloodGroup || 'Not provided'}
Mobile: ${formData.mobile || 'Not provided'}
Email: ${formData.email || 'Not provided'}
Relation: ${formData.relationType} - ${formData.relationName || 'Not provided'}
Address: ${formData.address}, ${formData.city}, ${formData.state} ${formData.pincode}
Document Type: ${formData.docType}

DOCUMENT TEXT (extracted via OCR/PDF):
${hasOcr ? ocrText : 'NO DOCUMENT TEXT AVAILABLE'}

Respond with this exact JSON structure:
{"overallScore":7,"verdict":"review","eligibility":{"ageEligible":true,"note":"Age is 21, eligible"},"documentSummary":"Aadhar card detected with name and address","verificationChecks":[{"field":"Name","formValue":"John Doe","docValue":"John M Doe","match":false}],"issues":["Middle name missing"],"recommendations":["Add middle name"],"summary":"Application is mostly complete."}`;

      const res = await fetch(`${API_URL}/api/chat/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: prompt, mode: 'normal' }),
      });

      if (!res.ok) throw new Error(`Server error ${res.status}`);

      const data = await res.json();
      const rawResponse = data.response;

      // Try to extract JSON from the response
      let parsed = null;
      try {
        parsed = JSON.parse(rawResponse);
      } catch {
        try {
          const jsonMatch = rawResponse.match(/```(?:json)?\s*([\s\S]*?)```/) || rawResponse.match(/(\{[\s\S]*\})/);
          if (jsonMatch) parsed = JSON.parse(jsonMatch[1].trim());
        } catch {
          parsed = null;
        }
      }

      // Normalize whatever JSON the AI returned into our display format
      if (parsed && typeof parsed === 'object') {
        const normalized = normalizeAiResponse(parsed);
        setReviewResult(normalized);
      } else {
        setReviewResult({ _isRawText: true, rawText: rawResponse });
      }

      setStep(3);
    } catch (err) {
      alert(`AI Review failed: ${err.message}. Please ensure the backend server is running.`);
    } finally {
      setAiLoading(false);
    }
  };

  /**
   * Normalize any AI JSON response into our report display format.
   */
  function normalizeAiResponse(data) {
    if (data.overallScore && data.verificationChecks) return data;

    const checks = [];
    const issues = [];
    const recs = [];

    if (data.verificationChecks) {
      checks.push(...data.verificationChecks);
    } else if (data.extractedData) {
      const ed = data.extractedData;
      const docText = data.documentText || {};
      if (ed.nameMatch !== undefined) checks.push({ field: 'Full Name', formValue: `${formData.firstName} ${formData.lastName}`, docValue: docText.name || 'From document', match: ed.nameMatch });
      if (ed.addressMatch !== undefined) checks.push({ field: 'Address', formValue: formData.address, docValue: docText.address || 'From document', match: ed.addressMatch });
      if (ed.mobileMatch !== undefined) checks.push({ field: 'Mobile', formValue: formData.mobile, docValue: docText.mobile || 'From document', match: ed.mobileMatch });
      if (ed.dobMatch !== undefined) checks.push({ field: 'Date of Birth', formValue: formData.dob, docValue: docText.dob || 'From document', match: ed.dobMatch });
    } else if (data.fields) {
      data.fields.forEach(f => checks.push({ field: f.label || f.field, formValue: f.formValue || '—', docValue: f.docValue || f.message || '—', match: f.status === 'ok' || f.match === true }));
    }

    if (data.issues) issues.push(...data.issues);
    else if (data.errors) Object.entries(data.errors).forEach(([k, v]) => { if (v && v !== 'none') issues.push(`${k}: ${v}`); });

    if (data.recommendations) recs.push(...data.recommendations);

    let docSummary = data.documentSummary || data.docScanResult || '';
    if (!docSummary && data.documentText) {
      const dt = data.documentText;
      docSummary = `Document: ${data.documentType || formData.docType}. Name: ${dt.name || 'N/A'}. ${dt.fatherName ? `Father: ${dt.fatherName}. ` : ''}${dt.address ? `Address: ${dt.address.substring(0, 80)}...` : ''}`;
    }

    const matchCount = checks.filter(c => c.match).length;
    const totalChecks = checks.length || 1;
    const autoScore = data.overallScore || Math.round((matchCount / totalChecks) * 10);

    return {
      overallScore: Math.max(1, Math.min(10, autoScore)),
      verdict: autoScore >= 8 ? 'ready' : autoScore >= 5 ? 'review' : 'incomplete',
      eligibility: data.eligibility || { ageEligible: age >= 18, note: `Applicant is ${age} years old${age >= 18 ? ', eligible to vote' : ', NOT eligible'}` },
      documentSummary: docSummary || null,
      verificationChecks: checks,
      issues: issues.length ? issues : null,
      recommendations: recs.length ? recs : null,
      summary: data.summary || `Verification complete. ${matchCount}/${totalChecks} fields matched.`
    };
  }

  const renderStep = () => {

    switch (step) {
      case 0:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-grid-2">
              <div className="form-group">
                <label>{t('registrationPage.firstName')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('First Name')}>💡</button></label>
                <input name="firstName" value={formData.firstName} onChange={handleInputChange} placeholder="As per ID document" />
              </div>
              <div className="form-group">
                <label>{t('registrationPage.lastName')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Last Name')}>💡</button></label>
                <input name="lastName" value={formData.lastName} onChange={handleInputChange} placeholder="Surname" />
              </div>
            </div>

            <div className="form-grid-3">
              <div className="form-group">
                <label>{t('registrationPage.dob')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Date of Birth')}>💡</button></label>
                <input type="date" name="dob" value={formData.dob} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>{t('registrationPage.age')}</label>
                <input value={age ? `${age} years` : '—'} readOnly className="readonly-input" />
              </div>
              <div className="form-group">
                <label>{t('registrationPage.gender')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Gender')}>💡</button></label>
                <select name="gender" value={formData.gender} onChange={handleInputChange}>
                  <option value="">Select</option>
                  {GENDERS.map(g => <option key={g}>{g}</option>)}
                </select>
              </div>
            </div>

            <div className="form-grid-2">
              <div className="form-group">
                <label>{t('registrationPage.bloodGroup')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Blood Group')}>💡</button></label>
                <select name="bloodGroup" value={formData.bloodGroup} onChange={handleInputChange}>
                  <option value="">Select</option>
                  {BLOOD_GROUPS.map(b => <option key={b}>{b}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label>{t('registrationPage.mobile')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Mobile Number')}>💡</button></label>
                <input name="mobile" value={formData.mobile} onChange={handleInputChange} placeholder="+91 XXXXX XXXXX" maxLength={13} />
              </div>
            </div>

            <div className="form-grid-2">
              <div className="form-group">
                <label>{t('registrationPage.relationType')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Relation Type (Father/Husband name)')}>💡</button></label>
                <select name="relationType" value={formData.relationType} onChange={handleInputChange}>
                  {RELATION_TYPES.map(r => <option key={r}>{r}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label>{t('registrationPage.relationName')}</label>
                <input name="relationName" value={formData.relationName} onChange={handleInputChange} placeholder="Name as per ID" />
              </div>
            </div>
          </div>
        );

      case 1:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-group">
              <label>{t('registrationPage.fullAddress')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Residential Address')}>💡</button></label>
              <textarea name="address" value={formData.address} onChange={handleInputChange} placeholder="House/Flat No, Street Name, Landmark..." rows="3" />
            </div>
            <div className="form-grid-3">
              <div className="form-group">
                <label>{t('registrationPage.city')}</label>
                <input name="city" value={formData.city} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>{t('registrationPage.state')}</label>
                <input name="state" value={formData.state} onChange={handleInputChange} />
              </div>
              <div className="form-group">
                <label>{t('registrationPage.pincode')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('PIN Code')}>💡</button></label>
                <input name="pincode" value={formData.pincode} onChange={handleInputChange} maxLength={6} placeholder="6-digit" />
              </div>
            </div>
            <div className="form-group">
              <label>{t('registrationPage.email')}</label>
              <input type="email" name="email" value={formData.email} onChange={handleInputChange} placeholder="For ECI notifications" />
            </div>
          </div>
        );

      case 2:
        return (
          <div className="form-section animate-slide-up">
            <div className="form-group">
              <label>{t('registrationPage.primaryId')} <button type="button" className="ai-info-btn" title="AI Help" onClick={() => getAiInfo('Identity and Age Proof document')}>💡</button></label>
              <select name="docType" value={formData.docType} onChange={handleInputChange}>
                <option>Aadhar Card</option>
                <option>PAN Card</option>
                <option>Driving License</option>
                <option>Passport</option>
                <option>Birth Certificate</option>
                <option>Bank Passbook</option>
              </select>
            </div>

            <div className="upload-container">
              <input
                type="file"
                id="file-upload"
                ref={fileRef}
                className="hidden-input"
                onChange={handleFileChange}
                accept="image/*,.pdf"
              />
              <label htmlFor="file-upload" className={`upload-placeholder glass ${ocrLoading ? 'scanning' : ''}`}>
                {ocrLoading ? (
                  <div className="ocr-progress">
                    <div className="ocr-spinner" />
                    <span>Scanning document... {ocrProgress}%</span>
                    <div className="ocr-bar"><div style={{ width: `${ocrProgress}%` }} /></div>
                  </div>
                ) : file ? (
                  <div className="file-success">
                    <span className="file-icon">📄</span>
                    <span className="file-name">✅ {file.name}</span>
                    {ocrText && !ocrText.startsWith('[') && (
                      <span className="ocr-badge">🔍 Text extracted</span>
                    )}
                  </div>
                ) : (
                  <div className="upload-prompt">
                    <span className="upload-icon">📁</span>
                    <span>{t('registrationPage.dragDrop')}</span>
                    <span className="upload-hint">{t('registrationPage.supportedFormats')}</span>
                  </div>
                )}
              </label>
            </div>

            {ocrText && (
              <details className="ocr-preview">
                <summary>🔍 {t('registrationPage.extractedText')}</summary>
                <pre>{ocrText}</pre>
              </details>
            )}
          </div>
        );

      case 3:
        return (
          <div className="form-section animate-slide-up">
            {reviewResult ? (
              <ReviewReport data={reviewResult} />
            ) : (
              <div className="review-placeholder">
                <span>{t('registrationPage.noReview')}</span>
              </div>
            )}
          </div>
        );

      default: return null;
    }
  };

  return (
    <main className="registration-page">
      <div className="registration-layout">
        {/* ---- Main Form ---- */}
        <div className="registration-main">
          <header className="registration-header">
            <h1>
              <span className="heading-neuro">{t('registrationPage.title').split(' ')[0]}</span>{' '}
              <span className="text-gradient">{t('registrationPage.title').split(' ')[1] || 'Hub'}</span>
            </h1>
            <p>{t('registrationPage.subtitle')}</p>
          </header>

          <div className="step-indicator">
            {FORM_STEPS.map((s, i) => (
              <div key={s.id} className={`step-item ${i === step ? 'active' : ''} ${i < step ? 'completed' : ''}`}>
                <span className="step-icon">{s.icon}</span>
                <span className="step-label">{t(`registrationPage.step${i+1}`)}</span>
              </div>
            ))}
          </div>

          <Card variant="glass" className="form-card">
            {renderStep()}

            {/* AI Info Bubble */}
            {aiResponse && (
              <div className="ai-bubble animate-fade-in">
                <div className="ai-bubble-header">
                  <span>🤖 About: <strong>{aiResponse.field}</strong></span>
                  <button onClick={() => setAiResponse(null)}>✕</button>
                </div>
                <p>{aiResponse.text}</p>
              </div>
            )}

            <div className="form-footer">
              {step > 0 && step < 3 && (
                <Button variant="secondary" onClick={() => { setStep(step - 1); setAiResponse(null); }}>{t('registrationPage.backBtn')}</Button>
              )}
              {step < 2 && (
                <Button variant="primary" onClick={() => { setStep(step + 1); setAiResponse(null); }}>{t('registrationPage.nextBtn')}</Button>
              )}
              {step === 2 && (
                <Button variant="primary" onClick={runAiReview} disabled={aiLoading || ocrLoading}>
                  {aiLoading ? t('registrationPage.analyzing') : t('registrationPage.genReview')}
                </Button>
              )}
              {step === 3 && (
                <Button variant="secondary" onClick={() => { setStep(0); setReviewResult(null); setFile(null); setOcrText(''); }}>
                  {t('registrationPage.startFresh')}
                </Button>
              )}
            </div>
          </Card>
        </div>

        {/* ---- Sidebar ---- */}
        <aside className="registration-sidebar">
          <Card variant="bento" className="video-panel">
            <h3>📖 Tutorial Hub</h3>
            <p className="panel-subtitle">Official guides for voter registration in India.</p>

            <div className="video-list">
              {TUTORIAL_VIDEOS.map(video => (
                <div key={video.id} className={`video-item glass ${activeVideo === video.id ? 'active' : ''}`}>
                  {activeVideo === video.id ? (
                    <div className="video-thumb">
                      <iframe
                        src={`https://www.youtube.com/embed/${video.videoId}?autoplay=1`}
                        title={video.title}
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                      />
                    </div>
                  ) : (
                    <button className="video-preview-btn" onClick={() => setActiveVideo(video.id)}>
                      <div className="yt-thumbnail">
                        <img
                          src={`https://img.youtube.com/vi/${video.videoId}/mqdefault.jpg`}
                          alt={video.title}
                        />
                        <div className="yt-play-overlay">▶</div>
                      </div>
                    </button>
                  )}
                  <div className="video-info">
                    <h4>{video.title}</h4>
                    <span>⏱️ {video.duration}</span>
                    {activeVideo === video.id && (
                      <button className="close-video" onClick={() => setActiveVideo(null)}>✕ Close</button>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <div className="official-link">
              <a href="https://voters.eci.gov.in/" target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm w-full">
                🏛️ Visit Official ECI Portal
              </a>
            </div>
          </Card>
        </aside>
      </div>
    </main>
  );
}
